language: php
services:
  - mysql

before_script:
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher
  - mailcatcher
  - cp .env.travis .env
  - mysql -e 'create database mijn_sv_helloworld_test;'
  - travis_retry composer self-update
  - composer install --no-interaction
  - php artisan key:generate

jobs:
  include:
    - name: "Code Quality"
      php:
        - 7.2
        - 7.3
      script: php artisan insights --no-interaction --min-quality=80 --min-architecture=80 --min-complexity=80
    - name: "Unit Tests"
      php:
        - 7.2
        - 7.3
      script: vendor/bin/phpunit
    - name: "Browser Tests"
      php:
        - 7.2
        - 7.3
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - ./vendor/laravel/dusk/bin/chromedriver-linux &
        - cp .env.testing .env
        - php artisan serve &
      script:
        - php artisan dusk

script:
  - php artisan insights --no-interaction --min-quality=80 --min-architecture=80 --min-complexity=80
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
